### ISSUE TITLE
Strange bug with whitespaces

### ISSUE THREAD

**Issue by ax3ghazy** [Skyus/Oak.js#3]
Instructions copied with tabs, possibly with a different number of spaces than 4, don't assemble successfully; the tabs are somehow read as a part of the instruction mnemonic and not seen as whitespace.

![image](https://user-images.githubusercontent.com/19731159/36078296-0d8899f0-0f7d-11e8-911e-081e7d2ea76d.png)
[bug.zip](https://github.com/Skyus/Oak.js/files/1714812/bug.zip)

**Comment by KarimIO** [comment]
We greatly appreciate you reporting this! We'll try to solve it as quickly as possible.

**Comment by donn** [comment]
A bug report with an ACTUAL TEST CASE!? I never thought I'd see the day...

**Comment by donn** [comment]
```js
-            let directives = lines[i].split(" ").filter(function(value: string){ return value.length > 0 });
+            let directives = lines[i].split(/\s+/).filter(function(value: string){ return value.length > 0 });
```

god im stupid

Marking for full rework during backport

**Comment by KarimIO** [comment]
Closing, as this issue has been fixed in the main branch.
